# Generated by Django 5.0.6 on 2024-07-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courses_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_id',
            field=models.PositiveSmallIntegerField(max_length=3),
        ),
    ]
