# Generated by Django 5.0.6 on 2024-07-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_courses_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_id',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
