# Generated by Django 5.0.6 on 2024-07-07 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_courses_course_description'),
        ('teacher', '0002_rename_last_name_teachers_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.PositiveSmallIntegerField()),
                ('lesson_description', models.TextField()),
                ('course_code', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='course_code', to='courses.courses')),
                ('teacher_code', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_code', to='teacher.teachers')),
            ],
        ),
    ]
