# Generated by Django 5.0.6 on 2024-07-07 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessons',
            old_name='lesson_id',
            new_name='lesson_level',
        ),
    ]
