# Generated by Django 5.0.6 on 2024-07-07 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_rename_lesson_id_lessons_lesson_level'),
        ('teacher', '0003_rename_teacher_id_teachers_teacher_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='teacher_code',
        ),
        migrations.AddField(
            model_name='lessons',
            name='teacher_tsc_code',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_tsc_code', to='teacher.teachers'),
        ),
    ]
