# Generated by Django 5.0.6 on 2024-07-07 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_remove_lessons_teacher_code_lessons_teacher_tsc_code'),
        ('teacher', '0004_remove_teachers_id_remove_teachers_teacher_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='teacher_tsc_code',
        ),
        migrations.AddField(
            model_name='lessons',
            name='teacher_code',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_code', to='teacher.teachers'),
        ),
    ]
