# Generated by Django 5.0.6 on 2024-07-07 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='last_name',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='course_id',
            new_name='teacher_id',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='first_name',
            new_name='teacher_name',
        ),
    ]
