# Generated by Django 5.0.6 on 2024-07-07 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_rename_last_name_teachers_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='teacher_id',
            new_name='teacher_code',
        ),
    ]
