# Generated by Django 5.0.6 on 2024-07-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_rename_teacher_id_teachers_teacher_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='id',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='teacher_code',
        ),
        migrations.AddField(
            model_name='teachers',
            name='code',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, default=3),
            preserve_default=False,
        ),
    ]
