# Generated by Django 5.0.6 on 2024-07-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_alter_teachers_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, default=2),
        ),
    ]
