# Generated by Django 5.0.6 on 2024-07-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_alter_teachers_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teachers',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
