# Generated by Django 5.0.6 on 2024-07-10 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_teachers_id_alter_teachers_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='code',
        ),
    ]
